### ISSUE TITLE
Error in `normalize(path)` function when `path` is `undefined`

### ISSUE THREAD

**Issue by zettadam** [solidjs/solid-app-router#57]
When I run my app in development mode (with `vite-plugin-solid`) I run into an issue where `normalize` function (found in `utils.js`) receives `undefined` as parameter. (This happens before path becomes `/` or any other string) 

The code in normalize function doesn't check if path is a string and is trying to use replace method which causes runtime error.

I don't see this error when I serve a built application, so it might be related to `solid-refresh`

Here's my `App` with the routing tree:

```jsx
import { Suspense, lazy } from 'solid-js'
import { Router, Routes, Route } from 'solid-app-router'

import AppHeader from './components/AppHeader'
import AppFooter from './components/AppFooter'

import './app.css'

const Home = lazy(() => import('./screens/home/Home'))

const ScreenOne = lazy(() => import('./screens/screen-one/ScreenOne'))
const ViewOne = lazy(() => import('./screens/screen-one/ViewOne'))
const ViewTwo = lazy(() => import('./screens/screen-one/ViewTwo'))
const ViewThree = lazy(() => import('./screens/screen-one/ViewThree'))

const ScreenTwo = lazy(() => import('./screens/screen-two/ScreenTwo'))
const ScreenThree = lazy(() => import('./screens/screen-three/ScreenThree'))


const NotFound = () => {
  return (
    <main>
      <h2>404</h2>
      <p>Path not found.</p>
    </main>
  )
}

const App = () => {
  return (
    <div class="app">
      <Router>
        <AppHeader />
        <Suspense fallback="Loading...">
          <Routes>
            <Route path="/screen-one" element={ <ScreenOne /> }>
              <Route path="/view-one" element={ <ViewOne /> } />
              <Route path="/view-two" element={ <ViewTwo /> } />
              <Route path="/view-three" element={ <ViewThree /> } />
              <Route path="/" element={ <ViewOne /> } />
            </Route>
            <Route path="/screen-two" element={ <ScreenTwo /> } />
            <Route path="/screen-three" element={ <ScreenThree /> } />
            <Route path="/" element={ <Home /> } />
            <Route path="/*all" element={ <NotFound /> } />
          </Routes>
        </Suspense>
        <AppFooter />
      </Router>
    </div>
  )
}

export default App
```

`AppHeader` component contains `Link` components:

```jsx
import { Link } from 'solid-app-router'

const AppHeader = () => {
  return (
    <header class="app-header">
      <h1><Link href="/">Home</Link></h1>
      <nav class="app-navigation">
        <ul>
          <li><Link href="/screen-one">Screen One</Link></li>
          <li><Link href="/screen-two">Screen Two</Link></li>
          <li><Link href="/screen-three">Screen Three</Link></li>
        </ul>
      </nav>
    </header>
  )
}

export default AppHeader
```

Attached is a debugging screenshot:
![Screenshot from 2021-12-06 07-52-00](https://user-images.githubusercontent.com/516382/144858257-8fac0ce0-2807-40b7-994d-5eb2d463c1db.png)

**Comment by rturnq** [comment]
Thanks for filing this. It looks like you are correct, `solid-refresh` is the cuprit. Downgrading `vite-plugin-solid` to `2.0.2` to use the old version of `solid-refresh` or disabling hot reloading is probably the easiest bandaid for the time being.

**Comment by zettadam** [comment]
@rturnq I set `hmr` option to `false` when instantiating `vite-plugin-solid` and that did not solve this issue (at least for me). I'll look into downgrading it. Thanks.

**Comment by rturnq** [comment]
The option is `hot`

```js
export default defineConfig({
  plugins: [solidPlugin({ hot: false })],
  build: {
    target: "esnext",
    polyfillDynamicImport: false,
  },
});
```

**Comment by zettadam** [comment]
Hmm... [documentation](https://github.com/solidjs/vite-plugin-solid#optionshmr) seems to be incorrect then, or am I referring to something else?

**Comment by rturnq** [comment]
Good catch, that documentation is incorrect.

**Comment by rturnq** [comment]
Version 0.1.14 of the router should resolve this issue and allow HRM with the latest version of `solid-refresh`.

**Comment by zettadam** [comment]
This is still broken. My dependencies are:

solid-js: **1.3.2**
solid-app-router: **0.2.0**
babel-preset-solid: **1.3.2**
vite-plugin-solid: **2.2.1**

**Comment by LXSMNSYC** [comment]
Any minimal reproduction to this issue? 

More specifically, do you have any Pascal-cased functions that isn't a component?

**Comment by zettadam** [comment]
Arghh... Solid JSX was the culprit--JSX comments don't seem to be supported when defining routes. Stuff like this:

```
<Routes>
  <Route path="/" element={<SomeComponent } /> {/* comment fail */}
</Routes>

**Comment by zettadam** [comment]
More specifically this error occurs when a comment is added to a nested route (3rd level)

**Comment by rturnq** [comment]
Ok, I see the issue. I was able to reproduce when there is a space between the comment and the Route. The router needs to be a more defensive in consuming the children of Routes. I'll fix this shortly.

For anyone interested here is a reproduction: https://playground.solidjs.com/?hash=-1591457517&version=1.2.6
If you look at the output tab, you can see an extra `" "` child is being passed to the Routes component which it attempts to process as a route definition.

**Comment by rturnq** [comment]
`solid-app-router` version 0.2.1 should resolve this issue.
